name: Deploy to AWS
on:
  workflow_run:
    workflows: [ "CD" ]
    types: [ completed ]
    branches: [ master ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Check code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.9

    - name: Run Terraform fmt check
      run: terraform fmt -check -diff -recursive

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Init Terraform
      run: |
        cd terraform/
        terraform init -input=false

    - name: Plan Terraform
      id: Plan
      continue-on-error: true
      run: |
        cd terraform/
        terraform plan -input=false -no-color